services:
  rollarr:
    image: gcr.io/distroless/static-debian12
    entrypoint: ["/app/rollarr"]
    ports:
      - "3001:3001"
    volumes:
      - ./rollarr:/app/rollarr:ro
      - /mnt/user/appdata/plex:/plex
      - /mnt/user/appdata/rollarr/devdb/:/data
    environment:
      - DB_PATH=/data/rollarr.db
      - ROLLARR_API_TOKEN=${ROLLARR_API_TOKEN:-}
      - SONARR_URL=${SONARR_URL:-}
      - SONARR_API_KEY=${SONARR_API_KEY:-}
      - PLEX_URL=${PLEX_URL:-}
      - PLEX_TOKEN=${PLEX_TOKEN:-}
      - PLEX_DB_PATH=${PLEX_DB_PATH:-}
      - SEERR_WEBHOOK_SECRET=${SEERR_WEBHOOK_SECRET:-}
    restart: unless-stopped
